"""3D LUT Generation

Generate 33³ 3D LUT grids, apply color pipelines, read/write .cube files,
and perform trilinear interpolation for image application.
"""

import numpy as np
import os

from .core import (
    vlog_to_linear,
    vgamut_to_rec709,
    apply_tone_curve,
    apply_color_grade,
    linear_to_display,
    M_VGAMUT_TO_REC709,
    DISPLAY_GAMMA,
)

DEFAULT_LUT_SIZE = 33


def generate_3dlut_grid(size=DEFAULT_LUT_SIZE):
    """Generate a 3D grid of input RGB values.

    Returns:
        points: (size**3, 3) array of all grid points in [0, 1]
    """
    values = np.linspace(0.0, 1.0, size, dtype=np.float64)
    r_grid, g_grid, b_grid = np.meshgrid(values, values, values, indexing='ij')
    points = np.column_stack([r_grid.ravel(), g_grid.ravel(), b_grid.ravel()])
    return points


def generate_vlog_lut(size=DEFAULT_LUT_SIZE, params=None):
    """Generate V-Log/V-Gamut → Preset → Rec.709 3D LUT.

    Pipeline:
      V-Log → invert V-Log → V-Gamut→Rec.709 matrix
      → tone curve → creative grade → display gamma

    Args:
        size: Grid resolution (default 33)
        params: Preset params dict (if None, returns neutral pass-through)

    Returns:
        (size, size, size, 3) float64 LUT array
    """
    input_points = generate_3dlut_grid(size)

    # 1. V-Log to scene-linear
    linear_vgamut = vlog_to_linear(input_points)

    # 2. V-Gamut to Rec.709 primaries
    linear_rec709 = vgamut_to_rec709(linear_vgamut)

    if params is None:
        # Neutral: just convert to display gamma
        display = linear_to_display(linear_rec709)
    else:
        # Full pipeline
        tonemapped = apply_tone_curve(linear_rec709, params)
        graded = apply_color_grade(tonemapped, params)
        display = linear_to_display(graded)

    return np.clip(display, 0.0, 1.0).reshape(size, size, size, 3)


def generate_standard_lut(size=DEFAULT_LUT_SIZE, params=None):
    """Generate Rec.709 → Preset → Rec.709 3D LUT (creative grade only).

    Pipeline:
      Rec.709 display → inverse display gamma → linear
      → tone curve → creative grade → display gamma

    Args:
        size: Grid resolution (default 33)
        params: Preset params dict

    Returns:
        (size, size, size, 3) float64 LUT array
    """
    input_points = generate_3dlut_grid(size)

    # 1. Inverse display gamma: Rec.709 display → scene-linear
    threshold = 0.04045
    linear_part = input_points / 12.92
    gamma_part = ((input_points + 0.055) / 1.055) ** DISPLAY_GAMMA
    linear_rec709 = np.where(input_points <= threshold, linear_part, gamma_part)

    if params is None:
        # Neutral: just re-apply display gamma
        display = linear_to_display(linear_rec709)
    else:
        tonemapped = apply_tone_curve(linear_rec709, params)
        graded = apply_color_grade(tonemapped, params)
        display = linear_to_display(graded)

    return np.clip(display, 0.0, 1.0).reshape(size, size, size, 3)


def write_cube_file(filename, lut_data, title="LUT"):
    """Write a 3D LUT in .cube format.

    Format:
      TITLE "title"
      LUT_3D_SIZE N
      DOMAIN_MIN 0.0 0.0 0.0
      DOMAIN_MAX 1.0 1.0 1.0
      r g b  (R changes fastest, then G, then B)
    """
    size = lut_data.shape[0]
    assert lut_data.shape == (size, size, size, 3), \
        f"Unexpected LUT shape: {lut_data.shape}"

    with open(filename, 'w') as f:
        f.write(f'# Film Emulation LUT\n')
        f.write(f'# Generated by lutex.py\n')
        f.write(f'# Grid: {size}³\n')
        f.write('\n')
        f.write(f'TITLE "{title}"\n')
        f.write(f'LUT_3D_SIZE {size}\n')
        f.write(f'DOMAIN_MIN 0.0 0.0 0.0\n')
        f.write(f'DOMAIN_MAX 1.0 1.0 1.0\n')
        f.write('\n')

        # .cube format: R changes fastest, then G, then B
        for bi in range(size):
            for gi in range(size):
                for ri in range(size):
                    r, g, b = lut_data[ri, gi, bi]
                    f.write(f'{r:.8f} {g:.8f} {b:.8f}\n')

    file_size = os.path.getsize(filename)
    print(f'  ✓ {filename} — {size}³ = {size**3} entries, {file_size:,} bytes')


def apply_lut_to_image(lut_data, image):
    """Apply a 3D LUT to an image using trilinear interpolation.

    Args:
        lut_data: (size, size, size, 3) float64 array, LUT values in [0, 1]
        image: (H, W, 3) float64 array, pixel values in [0, 1]

    Returns:
        (H, W, 3) float64 array with LUT applied
    """
    size = lut_data.shape[0]
    scale = size - 1

    image = np.clip(image, 0.0, 1.0)

    # Map [0,1] to LUT index space [0, scale]
    idx = image * scale
    i0 = np.floor(idx).astype(int)
    i1 = np.minimum(i0 + 1, scale)
    frac = idx - i0

    h, w = image.shape[:2]

    fr, fg, fb = frac[..., 0], frac[..., 1], frac[..., 2]
    r0, g0, b0 = i0[..., 0], i0[..., 1], i0[..., 2]
    r1, g1, b1 = i1[..., 0], i1[..., 1], i1[..., 2]

    # 8 corner samples
    c000 = lut_data[r0, g0, b0]
    c100 = lut_data[r1, g0, b0]
    c010 = lut_data[r0, g1, b0]
    c110 = lut_data[r1, g1, b0]
    c001 = lut_data[r0, g0, b1]
    c101 = lut_data[r1, g0, b1]
    c011 = lut_data[r0, g1, b1]
    c111 = lut_data[r1, g1, b1]

    # Interpolate along R
    fr3 = fr[..., np.newaxis]
    c00 = c000 * (1 - fr3) + c100 * fr3
    c01 = c001 * (1 - fr3) + c101 * fr3
    c10 = c010 * (1 - fr3) + c110 * fr3
    c11 = c011 * (1 - fr3) + c111 * fr3

    # Interpolate along G
    fg3 = fg[..., np.newaxis]
    c0 = c00 * (1 - fg3) + c10 * fg3
    c1 = c01 * (1 - fg3) + c11 * fg3

    # Interpolate along B
    fb3 = fb[..., np.newaxis]
    result = c0 * (1 - fb3) + c1 * fb3

    return np.clip(result, 0.0, 1.0)


def load_cube_file(filename):
    """Load a .cube LUT file.

    Returns:
        (size, size, size, 3) float64 array
    """
    with open(filename, 'r') as f:
        lines = f.readlines()

    size = None
    data_start = 0

    for i, line in enumerate(lines):
        line = line.strip()
        if line.upper().startswith('LUT_3D_SIZE'):
            size = int(line.split()[-1])
        elif line and not line.startswith('#') and not line.startswith('TITLE') \
                and not line.startswith('DOMAIN') and not line.startswith('LUT_3D_SIZE'):
            data_start = i
            break

    if size is None:
        raise ValueError(f"No LUT_3D_SIZE found in {filename}")

    data_lines = lines[data_start:]
    data = []
    for line in data_lines:
        line = line.strip()
        if line and not line.startswith('#'):
            parts = line.split()
            if len(parts) >= 3:
                data.append([float(parts[0]), float(parts[1]), float(parts[2])])

    expected = size ** 3
    if len(data) != expected:
        raise ValueError(f"Expected {expected} entries, got {len(data)}")

    lut = np.empty((size, size, size, 3), dtype=np.float64)
    idx = 0
    for bi in range(size):
        for gi in range(size):
            for ri in range(size):
                lut[ri, gi, bi] = data[idx]
                idx += 1
    return lut
